import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { Bell, Building2, CheckCircle2, ChevronRight, Circle, Download, KeyRound, Loader2, LogOut, Monitor, Moon, Palette, Pencil, Settings, Shield, ShieldCheck, Sun, User, Clock, Mail, Phone, BadgeCheck } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { apiFetch } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { LoadingState, ErrorState } from "@/components/states/DataStates";
import { useProfile, useSession } from "@/hooks/useSession";
import { useTheme } from "@/lib/theme";
import { LANGUAGES, useLanguage, type Language } from "@/lib/language";
import { ROLE_LABEL } from "@/lib/roles";
import { fmtDate, fmtDateTime } from "@/lib/procurement";
import { cn } from "@/lib/utils";

type Prefs = { tender_updates: boolean; bid_status: boolean; compliance_alerts: boolean; system: boolean; marketing: boolean };
const PREF_LABELS: [keyof Prefs, string, string][] = [["tender_updates", "Tender Updates", "Get notified about new tenders matching your categories"], ["bid_status", "Bid Status Updates", "Notifications about your bid submissions and results"], ["compliance_alerts", "Compliance Alerts", "Compliance check results and department review updates"], ["system", "System Notifications", "Important system updates and announcements"], ["marketing", "Marketing Communications", "Product updates, features and tips"]];
const VENDOR_FIELDS: [string, string][] = [["legal_name", "Organization Name"], ["trade_name", "Trade Name"], ["category", "Business Category"], ["gstin", "GSTIN"], ["pan", "PAN"], ["udyam_number", "Udyam / MSME Number"], ["address", "Registered Address"], ["city", "City"], ["state", "State"], ["pincode", "Pincode"], ["contact_email", "Contact Email"], ["contact_phone", "Contact Phone"]];

export function ProfileSettingsPage() {
  const { session } = useSession();
  const { data, isPending, error, refetch } = useProfile();
  const [view, setView] = useState<"profile" | "settings">("profile");
  const isVendor = data?.roles.includes("vendor") ?? false;
  if (isPending) return <LoadingState label="Loading your profile…" />;
  if (error) return <ErrorState error={error} onRetry={() => refetch()} />;
  if (!data?.profile || !session) return <ErrorState error={new Error("Profile not found")} />;
  return <div className="space-y-3">
    <div className="flex flex-wrap items-center gap-3 rounded-xl border border-border bg-card p-4"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary">{view === "profile" ? <User className="h-6 w-6" /> : <Settings className="h-6 w-6" />}</div><div><h1 className="font-display text-2xl font-bold">{view === "profile" ? "My Profile" : "Settings"}</h1><p className="text-sm text-muted-foreground">{view === "profile" ? `Manage your personal ${isVendor ? "and organization " : "and official "}information.` : "Manage your account preferences, security and application settings."}</p></div>
      <div className="ml-auto flex rounded-lg border border-border p-0.5">{(["profile", "settings"] as const).map((v) => <button key={v} onClick={() => setView(v)} className={cn("rounded-md px-3 py-1.5 text-xs font-semibold", view === v ? "bg-primary text-primary-foreground" : "text-muted-foreground")}>{v === "profile" ? "My Profile" : "Settings"}</button>)}</div></div>
    {view === "profile" ? <ProfileView isVendor={isVendor} onSettings={() => setView("settings")} /> : <SettingsView />}
  </div>;
}

function useActivity() {
  const { session } = useSession();
  return useQuery({ queryKey: ["my-activity", session?.user.id], enabled: Boolean(session), queryFn: async () => { const data = await apiFetch<any>("/api/audit/me?limit=8"); return data.entries; } });
}

function ProfileView({ isVendor, onSettings }: { isVendor: boolean; onSettings: () => void }) {
  const { session } = useSession(); const { data } = useProfile(); const qc = useQueryClient(); const p = data!.profile!;
  const uid = session!.user.id;
  const vendor = useQuery({ queryKey: ["my-vendor", uid], enabled: isVendor, queryFn: async () => { try { const data = await apiFetch<any>("/api/vendors/me"); return data; } catch (e) { return null; } } });
  const activity = useActivity();
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState<Record<string, string>>({});
  useEffect(() => { if (vendor.data) setForm(Object.fromEntries(VENDOR_FIELDS.map(([k]) => [k, String((vendor.data as Record<string, unknown>)[k] ?? "")]))); }, [vendor.data]);
  const save = useMutation({ mutationFn: async () => { if (!form["legal_name"]?.trim()) throw new Error("Organization name is required"); if (form["gstin"] && !/^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z\d]Z[A-Z\d]$/.test(form["gstin"])) throw new Error("GSTIN must be a valid 15-character GSTIN"); if (form["pan"] && !/^[A-Z]{5}\d{4}[A-Z]$/.test(form["pan"])) throw new Error("PAN must look like ABCDE1234F"); const payload = Object.fromEntries(Object.entries(form).map(([k, v]) => [k, v.trim() || null])) as Record<string, string | null>; await apiFetch("/api/vendors/me", { method: "PUT", body: JSON.stringify(payload) }); }, onSuccess: () => { toast.success("Organization details saved"); setEditing(false); qc.invalidateQueries({ queryKey: ["my-vendor"] }); qc.invalidateQueries({ queryKey: ["my-activity"] }); }, onError: (e: Error) => toast.error(e.message) });
  const name = p.full_name || session!.user.email!;
  const official: [string, string | null][] = [["Designation", p.designation], ["Ministry / Department", p.ministry_department], ["Employee / Official ID", p.employee_official_id], ["Office Location", p.office_location], ["Organisation", p.organisation], ["Approval Status", p.approval_status]];
  return <div className="space-y-3">
    <div className="grid gap-3 lg:grid-cols-[1.4fr_1fr]">
      <div className="flex flex-wrap items-center gap-5 rounded-xl border border-border bg-card p-5"><div className="flex h-24 w-24 items-center justify-center rounded-full bg-primary text-4xl font-bold text-primary-foreground">{name.slice(0, 1).toUpperCase()}</div><div className="space-y-1 text-xs"><p className="flex items-center gap-2 text-lg font-bold">{name}{(isVendor ? vendor.data?.onboarding_status === "verified" : p.approval_status === "approved") && <span className="rounded bg-success/15 px-2 py-0.5 text-[10px] text-success">Verified</span>}</p><p className="text-muted-foreground">{isVendor ? vendor.data?.legal_name ?? p.organisation : p.designation}</p><p className="flex items-center gap-1.5"><Mail className="h-3.5 w-3.5" />{session!.user.email}</p>{p.phone && <p className="flex items-center gap-1.5"><Phone className="h-3.5 w-3.5" />{p.phone}</p>}<p className="text-muted-foreground">Last sign-in: {fmtDateTime(session!.user.last_sign_in_at)}</p></div></div>
      <div className="grid grid-cols-2 gap-4 rounded-xl border border-border bg-card p-5 text-xs"><div><p className="text-muted-foreground">Role</p><p className="font-semibold">{data!.roles.map((r) => ROLE_LABEL[r]).join(", ") || "—"}</p></div><div><p className="text-muted-foreground">{isVendor ? "Registration Status" : "Access Status"}</p><p className="flex items-center gap-1 font-semibold capitalize"><CheckCircle2 className="h-3.5 w-3.5 text-success" />{isVendor ? vendor.data?.onboarding_status ?? "—" : p.approval_status}</p></div><div><p className="text-muted-foreground">{isVendor ? "Vendor ID" : "Official ID"}</p><p className="font-mono font-semibold">{isVendor ? vendor.data?.id.slice(0, 8).toUpperCase() ?? "—" : p.employee_official_id ?? "—"}</p></div><div><p className="text-muted-foreground">Member Since</p><p className="font-semibold">{fmtDate(p.created_at)}</p></div></div>
    </div>
    <div className="rounded-xl border border-border bg-card p-5">
      <div className="mb-3 flex items-center gap-2"><Building2 className="h-5 w-5 text-primary" /><div><p className="text-sm font-semibold">{isVendor ? "Organization Details" : "Official Details"}</p><p className="text-[11px] text-muted-foreground">{isVendor ? "Your registered organization information on GeMShield." : "Details submitted with your government access request."}</p></div>{isVendor && !editing && <Button size="sm" variant="outline" className="ml-auto" onClick={() => setEditing(true)}><Pencil className="mr-1 h-3.5 w-3.5" />Edit</Button>}</div>
      {isVendor ? vendor.isPending ? <LoadingState /> : vendor.error ? <ErrorState error={vendor.error} /> : editing ? <div className="grid gap-3 sm:grid-cols-2">{VENDOR_FIELDS.map(([k, l]) => <div key={k} className="space-y-1"><Label className="text-xs">{l}</Label><Input value={form[k] ?? ""} onChange={(e) => setForm({ ...form, [k]: k === "gstin" || k === "pan" ? e.target.value.toUpperCase() : e.target.value })} /></div>)}<div className="flex gap-2 sm:col-span-2"><Button onClick={() => save.mutate()} disabled={save.isPending}>{save.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Save details</Button><Button variant="outline" onClick={() => setEditing(false)}>Cancel</Button></div></div>
        : <table className="w-full text-xs"><tbody>{VENDOR_FIELDS.map(([k, l]) => <tr key={k} className="border-t border-border"><td className="w-56 bg-muted/40 px-3 py-2 text-muted-foreground">{l}</td><td className="px-3 py-2">{String((vendor.data as Record<string, unknown> | null)?.[k] ?? "") || <span className="text-muted-foreground">Not provided</span>}</td></tr>)}</tbody></table>
        : <table className="w-full text-xs"><tbody>{official.map(([l, v]) => <tr key={l} className="border-t border-border"><td className="w-56 bg-muted/40 px-3 py-2 text-muted-foreground">{l}</td><td className="px-3 py-2 capitalize-first">{v || <span className="text-muted-foreground">Not provided</span>}</td></tr>)}</tbody></table>}
    </div>
    <div className="grid gap-3 md:grid-cols-2">
      <div className="rounded-xl border border-border bg-card p-4"><p className="mb-3 flex items-center gap-2 text-sm font-semibold"><Clock className="h-4 w-4 text-primary" />Account Activity</p>{activity.isPending ? <LoadingState /> : !activity.data?.length ? <p className="text-xs text-muted-foreground">No recorded activity yet.</p> : <ol className="space-y-3 border-l border-border pl-4">{activity.data.map((a) => <li key={a.id} className="relative text-xs"><span className="absolute -left-[21px] top-1 h-2.5 w-2.5 rounded-full bg-primary" /><p className="font-semibold">{a.action}</p><p className="text-muted-foreground">{a.summary}</p><p className="text-[10px] text-muted-foreground">{fmtDateTime(a.created_at)}</p></li>)}</ol>}</div>
      <div className="rounded-xl border border-border bg-card p-4"><p className="mb-3 text-sm font-semibold">Quick Actions</p>{[["Edit Profile", Pencil, () => (isVendor ? setEditing(true) : onSettings())], ["Go to Settings", Settings, onSettings], ["Change Password", KeyRound, onSettings]].map(([l, I, fn]) => { const Icon = I as typeof Pencil; return <button key={l as string} onClick={fn as () => void} className="flex w-full items-center gap-2 border-b border-border py-2.5 text-left text-xs last:border-0 hover:text-primary"><Icon className="h-4 w-4 text-primary" />{l as string}<ChevronRight className="ml-auto h-3.5 w-3.5" /></button>; })}</div>
    </div>
  </div>;
}

function SettingsView() {
  const { session } = useSession(); const { data } = useProfile(); const p = data!.profile!;
  const { theme, setTheme } = useTheme(); const { language, setLanguage } = useLanguage();
  const qc = useQueryClient(); const navigate = useNavigate();
  const [tab, setTab] = useState<"account" | "security" | "notifications" | "appearance" | "privacy">("account");
  const [f, setF] = useState({ full_name: p.full_name ?? "", phone: p.phone ?? "", designation: p.designation ?? "", timezone: p.timezone ?? "Asia/Kolkata" });
  const [prefs, setPrefs] = useState<Prefs>({ tender_updates: true, bid_status: true, compliance_alerts: true, system: false, marketing: false, ...((p.notification_prefs ?? {}) as Partial<Prefs>) });
  const [density, setDensity] = useState(p.density ?? "default");
  const [pw, setPw] = useState({ current: "", next: "", confirm: "" });
  const upd = useMutation({ mutationFn: async (patch: Record<string, unknown>) => { await apiFetch("/api/profiles/me", { method: "PUT", body: JSON.stringify(patch) }); }, onSuccess: () => { toast.success("Settings saved"); qc.invalidateQueries({ queryKey: ["profile"] }); }, onError: (e: Error) => toast.error(e.message) });
  const changePw = useMutation({ mutationFn: async () => { if (pw.next.length < 8) throw new Error("New password must be at least 8 characters"); if (pw.next !== pw.confirm) throw new Error("Passwords do not match"); const { error } = await supabase.auth.updateUser({ password: pw.next, ...(pw.current ? { current_password: pw.current } : {}) } as Parameters<typeof supabase.auth.updateUser>[0]); if (error) throw error; await apiFetch("/api/audit", { method: "POST", body: JSON.stringify({ action: "Password changed", entity_type: "User Management", summary: "Password updated from Settings" }) }); }, onSuccess: () => { toast.success("Password updated"); setPw({ current: "", next: "", confirm: "" }); }, onError: (e: Error) => toast.error(e.message) });
  async function downloadData() { try { const data = await apiFetch("/api/profiles/export"); const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "gemshield-my-data.json"; a.click(); toast.success("Your data export has downloaded"); } catch (e: any) { toast.error("Failed to export data"); } }
  async function signOutAll() { await supabase.auth.signOut({ scope: "global" }); qc.clear(); navigate({ to: "/auth", replace: true }); }
  const checks: [string, boolean][] = [["Full name", Boolean(p.full_name)], ["Phone number", Boolean(p.phone)], ["Designation", Boolean(p.designation)], ["Organisation", Boolean(p.organisation || p.ministry_department)], ["Notification preferences", Boolean(p.notification_prefs)]];
  const pct = Math.round((checks.filter((c) => c[1]).length / checks.length) * 100);
  const tabs = [["account", "Account Settings", User], ["security", "Security", Shield], ["notifications", "Notifications", Bell], ["appearance", "Appearance", Palette], ["privacy", "Data & Privacy", ShieldCheck]] as const;
  return <div className="grid gap-3 lg:grid-cols-[1fr_300px]">
    <div className="space-y-3">
      <div className="flex gap-1 overflow-x-auto border-b border-border">{tabs.map(([k, l, I]) => <button key={k} onClick={() => setTab(k)} className={cn("flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-2 text-xs font-medium", tab === k ? "border-primary text-primary" : "border-transparent text-muted-foreground")}><I className="h-3.5 w-3.5" />{l}</button>)}</div>
      {tab === "account" && <Card title="Account Settings" sub="Update your account preferences and basic information." icon={User}><div className="grid gap-3 sm:grid-cols-2"><Field l="Full Name"><Input value={f.full_name} onChange={(e) => setF({ ...f, full_name: e.target.value })} /></Field><Field l="Email Address"><Input value={session!.user.email ?? ""} disabled /></Field><Field l="Phone Number"><Input value={f.phone} onChange={(e) => setF({ ...f, phone: e.target.value })} /></Field><Field l="Designation"><Input value={f.designation} onChange={(e) => setF({ ...f, designation: e.target.value })} /></Field>
        <Field l="Time Zone"><select className="h-9 w-full rounded-md border border-input bg-background px-2 text-sm" value={f.timezone} onChange={(e) => setF({ ...f, timezone: e.target.value })}>{["Asia/Kolkata", "UTC", "Asia/Dubai", "Asia/Singapore", "Europe/London"].map((z) => <option key={z}>{z}</option>)}</select></Field>
        <Field l="Language Preference"><select className="h-9 w-full rounded-md border border-input bg-background px-2 text-sm" value={language} onChange={(e) => { setLanguage(e.target.value as Language); void apiFetch("/api/profiles/me", { method: "PUT", body: JSON.stringify({ language: e.target.value }) }); }}>{LANGUAGES.map((l) => <option key={l.code} value={l.code}>{l.label}</option>)}</select></Field></div>
        <Button className="mt-3" disabled={upd.isPending} onClick={() => { if (!f.full_name.trim()) { toast.error("Full name is required"); return; } upd.mutate({ full_name: f.full_name.trim(), phone: f.phone.trim() || null, designation: f.designation.trim() || null, timezone: f.timezone }); }}>{upd.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Save Changes</Button></Card>}
      {tab === "security" && <Card title="Security" sub="Change your password and manage active sessions." icon={Shield}><div className="grid max-w-md gap-3"><Field l="Current password"><Input type="password" autoComplete="current-password" value={pw.current} onChange={(e) => setPw({ ...pw, current: e.target.value })} /></Field><Field l="New password"><Input type="password" autoComplete="new-password" value={pw.next} onChange={(e) => setPw({ ...pw, next: e.target.value })} /></Field><Field l="Confirm new password"><Input type="password" autoComplete="new-password" value={pw.confirm} onChange={(e) => setPw({ ...pw, confirm: e.target.value })} /></Field><Button onClick={() => changePw.mutate()} disabled={changePw.isPending || !pw.next}>{changePw.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Update password</Button></div>
        <div className="mt-5 flex flex-wrap items-center gap-2 border-t border-border pt-4 text-xs"><p className="flex-1 text-muted-foreground">Last sign-in {fmtDateTime(session!.user.last_sign_in_at)}</p><Button variant="outline" size="sm" onClick={signOutAll}><LogOut className="mr-1 h-4 w-4" />Sign out of all devices</Button></div></Card>}
      {tab === "notifications" && <Card title="Notification Preferences" sub="Choose what notifications you want to receive." icon={Bell}><ul className="divide-y divide-border">{PREF_LABELS.map(([k, l, d]) => <li key={k} className="flex items-center gap-3 py-3"><div className="flex-1"><p className="text-sm font-medium">{l}</p><p className="text-xs text-muted-foreground">{d}</p></div><Switch checked={prefs[k]} onCheckedChange={(v) => { const next = { ...prefs, [k]: v }; setPrefs(next); upd.mutate({ notification_prefs: next }); }} aria-label={l} /></li>)}</ul></Card>}
      {tab === "appearance" && <Card title="Appearance Settings" sub="Customize your viewing experience." icon={Palette}><p className="mb-2 text-xs font-semibold">Theme Mode</p><div className="grid max-w-lg grid-cols-3 gap-2">{([["light", "Light", Sun], ["dark", "Dark", Moon], ["system", "System", Monitor]] as const).map(([k, l, I]) => <Button key={k} variant={(k === "system" ? false : theme === k) ? "default" : "outline"} onClick={() => { const t = k === "system" ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light") : k; setTheme(t); void apiFetch("/api/profiles/me", { method: "PUT", body: JSON.stringify({ theme: t }) }); }}><I className="mr-2 h-4 w-4" />{l}</Button>)}</div>
        <p className="mb-2 mt-5 text-xs font-semibold">Interface Density</p><div className="flex flex-wrap gap-4 text-xs">{[["compact", "Compact"], ["default", "Default (Recommended)"], ["comfortable", "Comfortable"]].map(([k, l]) => <label key={k} className="flex items-center gap-1.5"><input type="radio" name="density" checked={density === k} onChange={() => { setDensity(k!); upd.mutate({ density: k }); }} />{l}</label>)}</div></Card>}
      {tab === "privacy" && <Card title="Data & Privacy" sub="Download a copy of your GeMShield data." icon={ShieldCheck}><p className="text-sm text-muted-foreground">Your export includes your profile, organisation details, bids, compliance checks, notifications and your own activity log.</p><Button className="mt-3" variant="outline" onClick={downloadData}><Download className="mr-2 h-4 w-4" />Download My Data</Button><p className="mt-4 text-xs text-muted-foreground">Account deactivation must be requested from the procurement administration because bid and audit records are retained for statutory audit.</p></Card>}
    </div>
    <aside className="space-y-3">
      <div className="rounded-xl border border-border bg-card p-4"><p className="mb-3 text-sm font-semibold">Profile Completion</p><div className="flex items-center gap-3"><div className="flex h-16 w-16 items-center justify-center rounded-full border-[6px] border-primary text-sm font-bold">{pct}%</div><p className="text-xs text-muted-foreground">{pct === 100 ? "Your profile is complete." : "Complete remaining details for better visibility."}</p></div><ul className="mt-3 space-y-2 text-xs">{checks.map(([l, ok]) => <li key={l} className="flex items-center gap-2">{ok ? <CheckCircle2 className="h-4 w-4 text-success" /> : <Circle className="h-4 w-4 text-muted-foreground" />}{l}</li>)}</ul></div>
      <div className="rounded-xl border border-border bg-card p-4"><p className="mb-2 text-sm font-semibold">Quick Actions</p>{[["Change Password", KeyRound, "security"], ["Notification Preferences", Bell, "notifications"], ["Download My Data", Download, "privacy"], ["Appearance", BadgeCheck, "appearance"]].map(([l, I, t]) => { const Icon = I as typeof KeyRound; return <button key={l as string} onClick={() => setTab(t as typeof tab)} className="flex w-full items-center gap-2 border-b border-border py-2.5 text-left text-xs last:border-0 hover:text-primary"><Icon className="h-4 w-4 text-primary" />{l as string}<ChevronRight className="ml-auto h-3.5 w-3.5" /></button>; })}</div>
    </aside>
  </div>;
}

function Card({ title, sub, icon: I, children }: { title: string; sub: string; icon: typeof User; children: React.ReactNode }) {
  return <div className="rounded-xl border border-border bg-card p-5"><div className="mb-4 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><I className="h-5 w-5" /></div><div><p className="text-sm font-semibold">{title}</p><p className="text-xs text-muted-foreground">{sub}</p></div></div>{children}</div>;
}
function Field({ l, children }: { l: string; children: React.ReactNode }) { return <div className="space-y-1"><Label className="text-xs">{l}</Label>{children}</div>; }
