import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Activity, ChevronLeft, Clock3, Code2, Cog, Copy, Download, ExternalLink, Eye, FileClock, Link2, MoreVertical, Search, ShieldAlert, User, Users } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { z } from "zod";
import { toast } from "sonner";
import { apiFetch } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { AuditEventDialog, type AuditLog } from "@/components/officer/AuditEventDialog";
import { EmptyState, ErrorState, LoadingState } from "@/components/states/DataStates";
import { fmtDateTime } from "@/lib/procurement";
import { useLanguage } from "@/lib/language";
import { WORKSPACE_TRANSLATIONS } from "@/lib/workspace-translations";
import { cn } from "@/lib/utils";
import { OFFICER_WORKFLOW_TRANSLATIONS } from "@/lib/officer-workflow-translations";

export const Route = createFileRoute("/_authenticated/officer/audit")({
  validateSearch:z.object({entity:z.string().optional()}),
  head:()=>({meta:[{title:"Audit Logs — GeMShield"},{name:"description",content:"Append-only record of procurement activity."},{property:"og:title",content:"Audit Logs — GeMShield"},{property:"og:description",content:"Append-only record of procurement activity."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AuditLogs,
});
type Log=AuditLog;
const COLORS=["var(--primary)","var(--success)","var(--warning)","var(--destructive)","var(--gold)","var(--info)","var(--muted-foreground)"];
const sevOf=(l:Log)=>String(l.metadata?.["severity"]??"info");
const kindOf=(l:Log)=>{const origin=String(l.metadata?.["origin"]??"");if(["deterministic_rule","ai_advisory","system"].includes(origin)||!l.actor_id)return "system";if(/sign|login|logout|password|role/i.test(l.action))return "security";return "user"};
const SEV:Record<string,string>={success:"bg-success/12 text-success",info:"bg-primary/10 text-primary",warning:"bg-warning/15 text-warning",error:"bg-destructive/10 text-destructive",critical:"bg-destructive/10 text-destructive"};

function related(log:Log):{label:string;to:string;params?:Record<string,string>}|null {
  const m=log.metadata??{}; const run=String(m["run_id"]??(log.entity_type==="Compliance Check"?log.entity_id??"":""));
  if(run)return{label:"compliance",to:"/officer/ai-compliance/$runId",params:{runId:run}};
  const tender=String(m["tender_id"]??(log.entity_type==="Tender Management"?log.entity_id??"":""));
  if(tender)return{label:"tender",to:"/officer/tenders/manage"};
  if(log.entity_type==="Human Review")return{label:"review",to:"/officer/human-review"};
  if(log.entity_type==="Final Decision")return{label:"decision",to:"/officer/decisions"};
  if(log.entity_type==="Rule Management")return{label:"rules",to:"/officer/rules"};
  return null;
}

function AuditLogs(){
  const {entity}=Route.useSearch();const {language}=useLanguage();const {common,audit:t}=WORKSPACE_TRANSLATIONS[language];
  const et=OFFICER_WORKFLOW_TRANSLATIONS[language].event; const [days,setDays]=useState(30);const [q,setQ]=useState(entity??"");const [mod,setMod]=useState("");const [role,setRole]=useState("");const [sev,setSev]=useState("");const [sel,setSel]=useState<Log|null>(null);const [actions,setActions]=useState<Log|null>(null);const [page,setPage]=useState(1);
  const logs=useQuery({queryKey:["audit",days],refetchInterval:3000,queryFn:async()=>{const data=await apiFetch<any>(`/api/audit?limit=2000`);return data.entries as Log[]}});
  const all=logs.data??[];const rows=useMemo(()=>all.filter(l=>(!mod||l.entity_type===mod)&&(!role||l.actor_role===role)&&(!sev||sevOf(l)===sev)&&(!q||`${l.actor_email} ${l.action} ${l.summary} ${l.entity_id} ${l.ip_address}`.toLowerCase().includes(q.toLowerCase()))),[all,mod,role,sev,q]);
  const per=10,pages=Math.max(1,Math.ceil(rows.length/per)),shown=rows.slice((page-1)*per,page*per);
  const trend=useMemo(()=>{const m=new Map<string,{d:string;user:number;system:number;security:number}>();for(let i=days-1;i>=0;i--){const d=new Date(Date.now()-i*864e5).toISOString().slice(0,10);m.set(d,{d:d.slice(5),user:0,system:0,security:0})}all.forEach(l=>{const e=m.get(l.created_at.slice(0,10));if(e)e[kindOf(l)]++});return[...m.values()]},[all,days]);
  const group=(fn:(l:Log)=>string)=>{const m=new Map<string,number>();all.forEach(l=>m.set(fn(l),(m.get(fn(l))??0)+1));return[...m.entries()].sort((a,b)=>b[1]-a[1]).map(([name,v])=>({name,v}))};const byMod=group(l=>l.entity_type??"Other"),bySev=group(sevOf);const count=(k:string)=>all.filter(l=>kindOf(l)===k).length;
  const exportCsv=()=>{const lines=[[t.timestamp,t.user,t.role,t.action,t.module,t.entity,t.severity].join(","),...rows.map(l=>[l.created_at,l.actor_email??common.system,l.actor_role??"",l.action,l.entity_type??"",l.summary??l.entity_id??"",sevOf(l)].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(","))];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/csv"}));a.download=`audit-logs-${days}d.csv`;a.click();URL.revokeObjectURL(a.href)};
  const copy=async(l:Log)=>{await navigator.clipboard.writeText(JSON.stringify(l,null,2));toast.success(common.copied)};
  const copyId=async(l:Log)=>{await navigator.clipboard.writeText(l.id);toast.success(common.copied)};
  const download=(l:Log)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(l,null,2)],{type:"application/json"}));a.download=`audit-${l.id}.json`;a.click();URL.revokeObjectURL(a.href)};
  const kpis=[[t.totalActivities,all.length,Activity,"bg-primary/10 text-primary"],[t.userActions,count("user"),Users,"bg-success/10 text-success"],[t.systemActions,count("system"),Cog,"bg-warning/15 text-warning"],[t.securityEvents,count("security"),ShieldAlert,"bg-destructive/10 text-destructive"]] as const;
  return <div className="space-y-3"><nav className="flex items-center gap-1 text-xs text-muted-foreground"><ChevronLeft className="h-3.5 w-3.5"/><Link to="/officer/dashboard" className="text-primary">{common.dashboard}</Link> › {t.title}</nav>
    <header className="flex flex-wrap items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileClock className="h-6 w-6"/></span><div><h1 className="font-display text-2xl font-bold">{t.title}</h1><p className="text-sm text-muted-foreground">{t.description}</p></div><select className="ml-auto h-9 rounded-md border border-input bg-card px-2 text-xs" value={days} onChange={e=>{setDays(Number(e.target.value));setPage(1)}}><option value={7}>{t.last7}</option><option value={30}>{t.last30}</option><option value={90}>{t.last90}</option><option value={365}>{t.last12Months}</option></select><Button variant="outline" size="sm" onClick={exportCsv} disabled={!rows.length}><Download className="mr-1 h-4 w-4"/>{t.export}</Button></header>
    {logs.isPending?<LoadingState label={common.loading}/>:logs.error?<ErrorState error={logs.error} onRetry={()=>logs.refetch()}/>:<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{kpis.map(([label,value,Icon,tone])=><div key={label} className="flex items-center gap-3 rounded-lg border border-border bg-card p-4"><span className={cn("flex h-11 w-11 items-center justify-center rounded-lg",tone)}><Icon className="h-5 w-5"/></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value.toLocaleString()}</p><p className="text-[10px] text-muted-foreground">{label===t.totalActivities?`${days} days`:`${all.length?((value/all.length)*100).toFixed(1):0}%`}</p></div></div>)}</div>
    <div className="grid gap-3 lg:grid-cols-[1.4fr_1fr_1fr]"><ChartCard title={t.trend}><ResponsiveContainer><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="d" tick={{fontSize:10}} stroke="var(--muted-foreground)"/><YAxis allowDecimals={false} tick={{fontSize:10}} stroke="var(--muted-foreground)"/><Tooltip contentStyle={{background:"var(--card)",border:"1px solid var(--border)",fontSize:12}}/><Area dataKey="user" name={t.userActions} stroke="var(--primary)" fill="var(--primary)" fillOpacity={.12}/><Area dataKey="system" name={t.systemActions} stroke="var(--success)" fill="var(--success)" fillOpacity={.08}/><Area dataKey="security" name={t.securityEvents} stroke="var(--warning)" fill="var(--warning)" fillOpacity={.08}/></AreaChart></ResponsiveContainer></ChartCard><Donut title={t.byModule} data={byMod} total={all.length} empty={t.noPeriod}/><Donut title={t.bySeverity} data={bySev} total={all.length} empty={t.noPeriod}/></div>
    <section className="rounded-lg border border-border bg-card"><div className="flex flex-wrap gap-2 p-3"><div className="relative min-w-56 flex-1"><Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder={t.searchPlaceholder} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div>{([[mod,setMod,t.allModules,[...new Set(all.map(l=>l.entity_type).filter(Boolean))]],[role,setRole,t.allUsers,[...new Set(all.map(l=>l.actor_role).filter(Boolean))]],[sev,setSev,t.allSeverities,["success","info","warning","error"]]] as const).map(([value,setter,label,opts])=><select key={label} className="h-8 rounded-md border border-input bg-background px-2 text-xs" value={value} onChange={e=>{setter(e.target.value);setPage(1)}}><option value="">{label}</option>{opts.map(o=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>)}</div>
      {!rows.length?<div className="p-4"><EmptyState title={common.noResults}/></div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-muted/50 text-left text-muted-foreground"><tr>{["#",t.timestamp,t.user,t.role,t.action,t.module,t.entity,t.severity,common.actions].map(h=><th key={h} className="px-3 py-2 font-medium">{h}</th>)}</tr></thead><tbody>{shown.map((l,i)=><tr key={l.id} className={cn("border-t border-border",sel?.id===l.id&&"bg-primary/5")}><td className="px-3 py-2">{(page-1)*per+i+1}</td><td className="whitespace-nowrap px-3 py-2">{fmtDateTime(l.created_at)}</td><td className="px-3 py-2">{l.actor_email??common.system}</td><td className="px-3 py-2 capitalize">{(l.actor_role??"system").replace(/_/g," ")}</td><td className="px-3 py-2 font-medium">{l.action}</td><td className="px-3 py-2">{l.entity_type??"—"}</td><td className="max-w-52 truncate px-3 py-2 text-muted-foreground">{l.summary??l.entity_id??"—"}</td><td className="px-3 py-2"><span className={cn("rounded px-2 py-0.5 font-semibold capitalize",SEV[sevOf(l)]??SEV["info"])}>{sevOf(l)}</span></td><td className="px-3 py-2"><div className="flex gap-1"><Button size="icon" variant="outline" className="h-7 w-7" aria-label={t.viewDetails} title={t.viewDetails} onClick={()=>setSel(l)}><Eye className="h-3.5 w-3.5"/></Button><Button size="icon" variant="ghost" className="h-7 w-7" aria-label={common.actions} title={common.actions} onClick={()=>setActions(l)}><MoreVertical className="h-3.5 w-3.5"/></Button></div></td></tr>)}</tbody></table></div>}
      <div className="flex items-center justify-between border-t border-border px-3 py-2 text-[11px] text-muted-foreground"><span>{t.showing} {rows.length?(page-1)*per+1:0}–{Math.min(page*per,rows.length)} / {rows.length} {t.activities}</span><div className="flex gap-1"><Button size="sm" variant="outline" className="h-7" disabled={page<=1} onClick={()=>setPage(page-1)}>{common.previous}</Button><span className="px-2 py-1">{page}/{pages}</span><Button size="sm" variant="outline" className="h-7" disabled={page>=pages} onClick={()=>setPage(page+1)}>{common.next}</Button></div></div></section></>}
    <AuditEventDialog log={sel} logs={all} onClose={()=>setSel(null)} copy={{common,audit:t,event:et}}/>
    <Sheet open={Boolean(actions)} onOpenChange={open=>{if(!open)setActions(null)}}><SheetContent className="w-full overflow-y-auto sm:max-w-md"><SheetHeader><SheetTitle>{common.actions}</SheetTitle><SheetDescription>{actions?.action}</SheetDescription></SheetHeader>{actions&&<div className="space-y-3 px-4"><div className="rounded-lg bg-primary/8 p-3"><p className="text-xs text-muted-foreground">{et.eventId}</p><p className="font-mono text-xs font-semibold">{actions.id}</p><p className="mt-1 text-xs text-muted-foreground">{fmtDateTime(actions.created_at)}</p></div><ActionGroup title={et.quickActions}><ActionButton icon={Eye} title={t.viewDetails} onClick={()=>{setSel(actions);setActions(null)}}/><ActionButton icon={Download} title={et.download} onClick={()=>download(actions)}/><ActionButton icon={Copy} title={et.copyId} onClick={()=>void copyId(actions)}/></ActionGroup><ActionGroup title={et.investigation}>{actions.entity_id&&<ActionButton icon={Link2} title={et.filterRelated} onClick={()=>{setQ(actions.entity_id??"");setPage(1);setActions(null)}}/>}{actions.actor_email&&<ActionButton icon={User} title={et.filterUser} onClick={()=>{setQ(actions.actor_email??"");setPage(1);setActions(null)}}/>}{related(actions)&&<div className="rounded-md border border-border"><RelatedLink log={actions} label={et.openRecord}/></div>}</ActionGroup><ActionGroup title={et.advanced}><ActionButton icon={Code2} title={et.rawJson} onClick={()=>{setSel(actions);setActions(null)}}/><ActionButton icon={Clock3} title={t.entityActivity} onClick={()=>{setQ(actions.entity_id??actions.id);setPage(1);setActions(null)}}/></ActionGroup></div>}<SheetFooter><Button variant="outline" onClick={()=>setActions(null)}>{common.close}</Button></SheetFooter></SheetContent></Sheet>
  </div>;
}
function ActionGroup({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border border-border p-2"><h3 className="px-2 py-1 text-sm font-semibold">{title}</h3><div className="space-y-1">{children}</div></section>}
function ActionButton({icon:Icon,title,onClick}:{icon:typeof Eye;title:string;onClick:()=>void}){return <Button variant="ghost" className="h-auto w-full justify-start py-2" onClick={onClick}><span className="mr-3 flex h-8 w-8 items-center justify-center rounded-md bg-primary/10 text-primary"><Icon className="h-4 w-4"/></span>{title}</Button>}
function ChartCard({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-lg border border-border bg-card p-4"><p className="mb-2 text-sm font-semibold">{title}</p><div className="h-52">{children}</div></div>}
function Donut({title,data,total,empty}:{title:string;data:{name:string;v:number}[];total:number;empty:string}){return <div className="rounded-lg border border-border bg-card p-4"><p className="mb-2 text-sm font-semibold">{title}</p>{data.length?<div className="flex items-center gap-3"><div className="relative h-40 w-40 shrink-0"><ResponsiveContainer><PieChart><Pie data={data} dataKey="v" innerRadius={45} outerRadius={70} strokeWidth={0}>{data.map((x,i)=><Cell key={x.name} fill={COLORS[i%COLORS.length]}/>)}</Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center"><b>{total}</b></div></div><ul className="space-y-1 text-[11px]">{data.slice(0,7).map((x,i)=><li key={x.name} className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full" style={{background:COLORS[i%COLORS.length]}}/><span className="capitalize">{x.name}</span><span className="text-muted-foreground">{total?Math.round(x.v/total*100):0}% ({x.v})</span></li>)}</ul></div>:<p className="text-xs text-muted-foreground">{empty}</p>}</div>}
function RelatedLink({log,label}:{log:Log;label:string}){const r=related(log);if(!r)return null;if(r.params)return <Link to={r.to as "/officer/ai-compliance/$runId"} params={r.params as {runId:string}}><ExternalLink className="mr-2 h-4 w-4"/>{label}</Link>;return <Link to={r.to as "/officer/rules"}><ExternalLink className="mr-2 h-4 w-4"/>{label}</Link>}