import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BarChart3, Building2, CalendarDays, CheckCircle2, ClipboardList, FilePlus2, FileSearch, Gavel, Lightbulb, ListChecks, ShieldAlert, ShieldCheck, Users, UsersRound } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { DashboardCard, CompactEmpty } from "@/components/dashboard/DashboardCard";
import { ErrorState, LoadingState } from "@/components/states/DataStates";
import { useProfile, useSession } from "@/hooks/useSession";
import { useLanguage } from "@/lib/language";
import { DASHBOARD_TRANSLATIONS } from "@/lib/dashboard-translations";

export const Route=createFileRoute("/_authenticated/officer/dashboard")({head:()=>({meta:[{title:"Officer Dashboard — GeMShield"},{name:"description",content:"Monitor tenders, bid verification, flagged reviews and final procurement decisions."},{property:"og:title",content:"Officer Dashboard — GeMShield"},{property:"og:description",content:"Monitor tenders, bid verification, flagged reviews and final procurement decisions."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:OfficerDashboard});

function Metric({icon:Icon,label,value,tone="blue"}:{icon:typeof ClipboardList;label:string;value:string;tone?:"blue"|"green"|"orange"|"purple"|"red"}){const colors={blue:"bg-info/10 text-info",green:"bg-success/10 text-success",orange:"bg-warning/15 text-warning",purple:"bg-secondary text-primary",red:"bg-destructive/10 text-destructive"};return <div className="flex min-h-24 items-center gap-3 rounded-lg border border-border bg-card p-4 shadow-[var(--shadow-card)]"><span className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-full ${colors[tone]}`}><Icon className="h-6 w-6"/></span><span><small className="block text-[11px] text-muted-foreground">{label}</small><b className="mt-1 block text-2xl leading-none text-foreground">{value}</b></span></div>}
function OfficerDashboard(){const {language}=useLanguage();const t=DASHBOARD_TRANSLATIONS[language];const o=t.officer;const {session}=useSession();const {data:profile}=useProfile();const userId=session?.user.id;const name=profile?.profile?.full_name||session?.user.email||"";const department=profile?.profile?.ministry_department||profile?.profile?.organisation;
 const vendors=useQuery({queryKey:["officer","vendors","count"],enabled:Boolean(userId),queryFn:async()=>{const data=await apiFetch<any>("/api/vendors/count");return data.count??0;}});
 const activity=useQuery({queryKey:["officer","audit","recent"],enabled:Boolean(userId),queryFn:async()=>{const data=await apiFetch<any>("/api/audit?limit=5");return data.entries;}});
 const notifications=useQuery({queryKey:["officer","notifications","recent",userId],enabled:Boolean(userId),queryFn:async()=>{const data=await apiFetch<any>("/api/notifications?limit=4");return data.notifications;}});
 const date=new Intl.DateTimeFormat(language==="en"?"en-IN":language,{dateStyle:"medium"}).format(new Date());
 return <div className="mx-auto max-w-[1320px] space-y-2.5">
  <section className="flex flex-wrap items-center gap-4 rounded-lg border border-border bg-card px-5 py-4 shadow-[var(--shadow-card)]"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-info/10 text-info"><ClipboardList className="h-6 w-6"/></span><div className="min-w-0"><h1 className="font-display text-2xl font-bold">{o.welcome}{name?`, ${name}`:""}</h1><p className="text-xs text-muted-foreground">{o.intro}</p></div><div className="ml-auto flex flex-wrap gap-2"><div className="flex min-w-40 items-center gap-2 rounded-md border border-border bg-background px-3 py-2"><CalendarDays className="h-4 w-4 text-info"/><span><small className="block text-[9px] text-muted-foreground">{o.date}</small><b className="block text-[10px]">{date}</b></span></div><div className="flex min-w-52 items-center gap-2 rounded-md border border-border bg-background px-3 py-2"><Building2 className="h-4 w-4 text-info"/><span className="min-w-0"><small className="block text-[9px] text-muted-foreground">{o.department}</small><b className="block max-w-48 truncate text-[10px]">{department||t.states.empty}</b></span></div></div></section>
  <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5"><Metric icon={ClipboardList} label={o.totalTenders} value="—"/><Metric icon={UsersRound} label={o.bidsReceived} value="—" tone="green"/><Metric icon={ShieldCheck} label={o.verifiedBids} value="—" tone="orange"/><Metric icon={ShieldAlert} label={o.flagged} value="—" tone="red"/><Metric icon={Users} label={o.registeredVendors} value={vendors.isPending?"…":vendors.error?"!":String(vendors.data??0)} tone="purple"/></div>
  <div className="grid gap-2.5 xl:grid-cols-[1.45fr_.86fr_.8fr]"><DashboardCard icon={BarChart3} title={o.tenderOverview} subtitle={o.tenderOverviewSub} action={<Button variant="outline" size="sm">{o.period}</Button>}><div className="flex min-h-56 items-center justify-center border-t border-border p-5 text-center"><div><BarChart3 className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-2 text-xs font-semibold">{o.noData}</p><p className="mt-1 text-[10px] text-muted-foreground">{o.noTableHelp}</p></div></div></DashboardCard>
   <DashboardCard icon={ShieldCheck} title={o.complianceStatus}><CompactEmpty icon={ShieldCheck} title={o.noData} description={o.noTableHelp}/></DashboardCard>
   <DashboardCard icon={Lightbulb} title={o.aiInsights} action={<Button variant="ghost" size="sm" asChild><Link to="/officer/ai-compliance">{o.viewAll}<ArrowRight className="ml-1 h-3.5 w-3.5"/></Link></Button>}><CompactEmpty icon={Lightbulb} title={o.noInsights} description={o.noInsightsHelp}/></DashboardCard></div>
  <div className="grid gap-2.5 xl:grid-cols-[1fr_300px]"><DashboardCard title={o.recentTenders} action={<Button variant="ghost" size="sm" asChild><Link to="/officer/tenders/manage">{o.viewAll}<ArrowRight className="ml-1 h-3.5 w-3.5"/></Link></Button>}><div className="grid grid-cols-4 border-y border-border bg-muted/40 text-center text-[10px]">{[o.recentTenders,o.recentBids,o.humanReview,o.activity].map((x,i)=><span key={x} className={i===0?"border-b-2 border-primary px-2 py-2 font-semibold text-primary":"px-2 py-2 text-muted-foreground"}>{x}</span>)}</div>{activity.isPending?<div className="p-3"><LoadingState label={t.states.loading}/></div>:activity.error?<div className="p-3"><ErrorState error={activity.error} onRetry={()=>activity.refetch()}/></div>:activity.data?.length?<div className="divide-y divide-border">{activity.data.map(e=><div key={e.id} className="grid grid-cols-[1fr_auto] gap-3 px-4 py-3 text-[11px]"><span><b className="block">{e.summary||e.action}</b><small className="text-muted-foreground">{e.actor_email||"System"}</small></span><time className="text-muted-foreground">{new Date(e.created_at).toLocaleDateString(language==="en"?"en-IN":language)}</time></div>)}</div>:<CompactEmpty icon={ClipboardList} title={o.noTable} description={o.noTableHelp}/>}</DashboardCard>
   <DashboardCard icon={ListChecks} tone="red" title={o.pending} action={<Button variant="ghost" size="sm" asChild><Link to="/officer/notifications">{o.viewAll}<ArrowRight className="ml-1 h-3.5 w-3.5"/></Link></Button>}>{notifications.isPending?<div className="p-3"><LoadingState label={t.states.loading}/></div>:notifications.error?<div className="p-3"><ErrorState error={notifications.error} onRetry={()=>notifications.refetch()}/></div>:notifications.data?.length?<ul className="divide-y divide-border border-t border-border">{notifications.data.map(n=><li key={n.id} className="p-3"><b className="text-[11px]">{n.title}</b>{n.body&&<p className="text-[10px] text-muted-foreground">{n.body}</p>}</li>)}</ul>:<CompactEmpty icon={CheckCircle2} title={o.noPending} description={o.noPendingHelp}/>}</DashboardCard></div>
  <section className="rounded-lg border border-border bg-card p-3 shadow-[var(--shadow-card)]"><h2 className="mb-2 text-xs font-bold">{o.quick}</h2><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{[{Icon:FilePlus2,title:o.create,sub:o.createHelp,to:"/officer/tenders/create" as const},{Icon:ClipboardList,title:o.manage,sub:o.manageHelp,to:"/officer/tenders/manage" as const},{Icon:FileSearch,title:o.verify,sub:o.verifyHelp,to:"/officer/bids" as const},{Icon:Users,title:o.manageVendors,sub:o.vendorsHelp,to:"/officer/vendors" as const},{Icon:BarChart3,title:o.generate,sub:o.generateHelp,to:"/officer/reports" as const}].map(({Icon,title,sub,to})=><Link key={to} to={to} className="flex min-h-16 items-center gap-3 rounded-md border border-border bg-muted/30 p-3 transition-colors hover:bg-accent"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-info/10 text-info"><Icon className="h-5 w-5"/></span><span className="min-w-0"><b className="block text-[11px]">{title}</b><small className="block text-[9px] leading-snug text-muted-foreground">{sub}</small></span><ArrowRight className="ml-auto h-3.5 w-3.5 text-info"/></Link>)}</div></section>
 </div>}
