import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ChevronLeft, Gavel, ShieldCheck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { EmptyState, ErrorState, LoadingState } from "@/components/states/DataStates";
import { fmtDateTime } from "@/lib/procurement";
import { cn } from "@/lib/utils";
import { useLanguage } from "@/lib/language";
import { OFFICER_WORKFLOW_TRANSLATIONS } from "@/lib/officer-workflow-translations";
import { apiFetch } from "@/lib/api";

export const Route = createFileRoute("/_authenticated/officer/decisions")({ head: () => ({ meta: [{ title: "Final Decisions — GeMShield" }, { name: "description", content: "Officer final decisions and immutable Bid Passports." }] }), component: Decisions });
type Related<T> = T | T[] | null;
type Row = { id: string; bid_id: string; score: number | null; verdict: string | null; file_name: string; completed_at: string | null; officer_status: string | null; bid: Related<{ id: string; status: string; submitted_at: string | null }>; tender: Related<{ title: string; reference_no: string }>; vendor: { full_name: string | null; email: string | null } | null; decision: Related<{ id: string; decision: string; justification: string; decision_hash: string; decided_at: string }>; review: Related<{ status: string }> };
const one=<T,>(value:Related<T>):T|null=>Array.isArray(value)?value[0]??null:value;
const many=<T,>(value:Related<T>):T[]=>Array.isArray(value)?value:value?[value]:[];

function Decisions() {
  const qc = useQueryClient(); const {language}=useLanguage(); const t=OFFICER_WORKFLOW_TRANSLATIONS[language].decisions; const [selected, setSelected] = useState<Row | null>(null); const [why, setWhy] = useState("");
  const q = useQuery({ queryKey: ["decision-candidates"], queryFn: async () => { return apiFetch<Row[]>("/api/decision-candidates"); } });
  const finalize = useMutation({ mutationFn: async (decision: "compliant" | "non_compliant") => { if (!selected?.bid_id) throw new Error(t.linkedError); if (why.trim().length < 10) throw new Error(t.justificationError); await apiFetch("/api/decisions/", { method: "POST", body: JSON.stringify({ bid_id: selected.bid_id, decision, justification: why.trim() }) }); }, onSuccess: async () => { toast.success(t.success); setSelected(null); setWhy(""); await qc.invalidateQueries({ queryKey: ["decision-candidates"] }); }, onError: (e: Error) => toast.error(e.message) });
  return <div className="space-y-3"><nav className="flex items-center gap-1 text-xs text-muted-foreground"><ChevronLeft className="h-3.5 w-3.5" /><Link to="/officer/dashboard" className="text-primary">Dashboard</Link> › {t.title}</nav><header className="flex items-center gap-3 rounded-lg border border-border bg-card p-4"><span className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary"><Gavel className="h-6 w-6" /></span><div><h1 className="font-display text-2xl font-bold">{t.title}</h1><p className="text-sm text-muted-foreground">{t.description}</p></div></header>
    {q.isPending ? <LoadingState label={t.loading} /> : q.error ? <ErrorState error={q.error} onRetry={() => q.refetch()} /> : !q.data.length ? <EmptyState title={t.emptyTitle} description={t.emptyDescription} /> : <div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full text-xs"><thead className="bg-muted/50 text-left text-muted-foreground"><tr>{[t.tender,t.vendor,t.evidence,t.score,t.review,t.decision,t.completed,""].map((h) => <th key={h} className="px-3 py-2 font-medium">{h}</th>)}</tr></thead><tbody>{q.data.map((r) => { const d=one(r.decision), blocked=many(r.review).some((x)=>x.status!=="resolved"), tender=one(r.tender); return <tr key={r.id} className="border-t border-border"><td className="px-3 py-2"><b>{tender?.reference_no ?? "—"}</b><span className="block text-muted-foreground">{tender?.title ?? "—"}</span></td><td className="px-3 py-2">{r.vendor?.full_name ?? r.vendor?.email ?? t.vendor}</td><td className="px-3 py-2">{r.file_name}</td><td className="px-3 py-2"><b>{r.score ?? "—"}</b><span className="block capitalize text-muted-foreground">{r.verdict?.replace(/_/g," ") ?? "—"}</span></td><td className="px-3 py-2">{blocked ? <span className="text-warning">{t.pending}</span> : t.clear}</td><td className="px-3 py-2">{d ? <span className={cn("rounded px-2 py-1 font-semibold capitalize",d.decision==="compliant"?"bg-success/10 text-success":"bg-destructive/10 text-destructive")}>{d.decision.replace(/_/g," ")}</span> : t.pending}</td><td className="px-3 py-2">{fmtDateTime(r.completed_at)}</td><td className="px-3 py-2"><Button size="sm" variant="outline" disabled={Boolean(d)||blocked} onClick={() => setSelected(r)}>{d ? t.finalized : blocked ? t.reviewFirst : t.decide}</Button></td></tr>; })}</tbody></table></div>}
    {selected && <section className="rounded-lg border border-primary/30 bg-card p-4"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" /><h2 className="font-semibold">{t.panelTitle}</h2><Button variant="outline" size="sm" className="ml-auto" asChild><Link to="/officer/ai-compliance/$runId" params={{runId:selected.id}}>{t.inspect}</Link></Button></div><p className="mt-1 text-xs text-muted-foreground">{t.panelDescription}</p><Textarea className="mt-3" rows={3} value={why} onChange={(e)=>setWhy(e.target.value)} placeholder={t.justification}/><div className="mt-2 flex flex-wrap gap-2"><Button className="bg-success text-success-foreground" disabled={finalize.isPending} onClick={()=>finalize.mutate("compliant")}><CheckCircle2 className="mr-1 h-4 w-4"/>{t.approve}</Button><Button variant="destructive" disabled={finalize.isPending} onClick={()=>finalize.mutate("non_compliant")}><XCircle className="mr-1 h-4 w-4"/>{t.reject}</Button><Button variant="outline" onClick={()=>setSelected(null)}>Cancel</Button></div></section>}
  </div>;
}