import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ChevronLeft, Eye, FileSearch, Loader2, Scale } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { EmptyState, ErrorState, LoadingState } from "@/components/states/DataStates";
import { fmtDateTime } from "@/lib/procurement";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/officer/human-review")({
  head: () => ({ meta: [{ title: "Human Review Queue — GeMShield" }, { name: "description", content: "Manual verification cases generated from real compliance evidence." }] }),
  component: HumanReview,
});

type CaseRow = { id: string; run_id: string; bid_id: string | null; priority: string; status: string; trigger_reason: string; created_at: string; resolution: string | null; justification: string | null; run: { file_name: string; score: number | null; verdict: string | null; ai_confidence: number | null } | null; tender: { title: string; reference_no: string } | null; vendor: { full_name: string | null; email: string | null } | null };
const tone: Record<string, string> = { high: "bg-destructive/10 text-destructive", medium: "bg-warning/15 text-warning", low: "bg-primary/10 text-primary", resolved: "bg-success/10 text-success" };

function HumanReview() {
  const qc = useQueryClient(); const [tab, setTab] = useState("all"); const [selected, setSelected] = useState<CaseRow | null>(null); const [note, setNote] = useState("");
  const cases = useQuery({ queryKey: ["human-review-cases"], queryFn: async () => { const { data, error } = await supabase.from("human_review_cases").select("*").order("created_at", { ascending: false }); if (error) throw error; if (!data?.length) return [] as CaseRow[]; const vendorIds=[...new Set(data.map((x)=>x.vendor_user_id))], runIds=data.map((x)=>x.run_id), tenderIds=[...new Set(data.map((x)=>x.tender_id).filter((x):x is string=>Boolean(x)))]; const [{data:profiles,error:pe},{data:runs,error:re},{data:tenders,error:te}]=await Promise.all([supabase.from("profiles").select("id,full_name,email").in("id",vendorIds),supabase.from("compliance_runs").select("id,file_name,score,verdict,ai_confidence").in("id",runIds),tenderIds.length?supabase.from("tenders").select("id,title,reference_no").in("id",tenderIds):Promise.resolve({data:[],error:null})]); if(pe||re||te)throw pe??re??te; const byVendor=new Map((profiles??[]).map((p)=>[p.id,p])),byRun=new Map((runs??[]).map((r)=>[r.id,r])),byTender=new Map((tenders??[]).map((t)=>[t.id,t])); return data.map((x)=>({...x,vendor:byVendor.get(x.vendor_user_id)??null,run:byRun.get(x.run_id)??null,tender:x.tender_id?byTender.get(x.tender_id)??null:null})) as unknown as CaseRow[]; } });
  const rows = useMemo(() => (cases.data ?? []).filter((x) => tab === "all" || (tab === "reviewed" ? x.status === "resolved" : x.priority === tab)), [cases.data, tab]);
  const action = useMutation({ mutationFn: async (kind: string) => { if (!selected) throw new Error("Select a case."); if (["override", "clarification", "escalate"].includes(kind) && note.trim().length < 10) throw new Error("Enter a justification of at least 10 characters."); const { error } = await supabase.rpc("record_human_review_action", { _case_id: selected.id, _action: kind, _justification: note.trim() }); if (error) throw error; }, onSuccess: async () => { toast.success("Review action recorded in the audit trail"); setNote(""); setSelected(null); await qc.invalidateQueries({ queryKey: ["human-review-cases"] }); }, onError: (e: Error) => toast.error(e.message) });
  return <div className="space-y-3"><nav className="flex items-center gap-1 text-xs text-muted-foreground"><ChevronLeft className="h-3.5 w-3.5" /><Link to="/officer/dashboard" className="text-primary">Dashboard</Link> › Human Review</nav>
    <header className="flex items-center gap-3 rounded-xl border border-border bg-card p-4"><span className="flex h-12 w-12 items-center justify-center rounded-lg bg-warning/15 text-warning"><Scale className="h-6 w-6" /></span><div><h1 className="font-display text-2xl font-bold">Human Review Queue</h1><p className="text-sm text-muted-foreground">AI is advisory. Officers resolve ambiguous, conflicting, missing or low-confidence evidence.</p></div></header>
    <div className="flex gap-1 overflow-auto border-b border-border">{["all","high","medium","low","reviewed"].map((x) => <button key={x} onClick={() => setTab(x)} className={cn("border-b-2 px-4 py-2 text-xs font-semibold capitalize", tab === x ? "border-primary text-primary" : "border-transparent text-muted-foreground")}>{x}</button>)}</div>
    {cases.isPending ? <LoadingState label="Loading review cases…" /> : cases.error ? <ErrorState error={cases.error} onRetry={() => cases.refetch()} /> : !rows.length ? <EmptyState title="No human review cases" description="Cases appear automatically when a real completed check has ambiguous, conflicting, missing or low-confidence evidence." /> : <div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full text-xs"><thead className="bg-muted/50 text-left text-muted-foreground"><tr>{["Case","Vendor / Tender","Document","Reason","Priority","Status","Created",""].map((h) => <th key={h} className="px-3 py-2 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={r.id} className="border-t border-border"><td className="px-3 py-2 font-mono">{r.id.slice(0,8)}</td><td className="px-3 py-2"><b>{r.vendor?.full_name ?? r.vendor?.email ?? "Vendor"}</b><span className="block text-muted-foreground">{r.tender ? `${r.tender.reference_no} · ${r.tender.title}` : "Standalone compliance check"}</span></td><td className="px-3 py-2">{r.run?.file_name ?? "—"}<span className="block text-muted-foreground">Score {r.run?.score ?? "—"} · Confidence {r.run?.ai_confidence == null ? "—" : `${Math.round(r.run.ai_confidence * 100)}%`}</span></td><td className="max-w-72 px-3 py-2">{r.trigger_reason}</td><td className="px-3 py-2"><span className={cn("rounded px-2 py-1 font-semibold capitalize", tone[r.priority])}>{r.priority}</span></td><td className="px-3 py-2 capitalize">{r.status.replace(/_/g," ")}</td><td className="px-3 py-2 whitespace-nowrap">{fmtDateTime(r.created_at)}</td><td className="px-3 py-2"><Button size="icon" variant="outline" className="h-7 w-7" onClick={() => setSelected(r)} aria-label="Review case"><Eye className="h-3.5 w-3.5" /></Button></td></tr>)}</tbody></table></div>}
    {selected && <section className="rounded-xl border border-primary/30 bg-card p-4"><div className="flex items-start gap-3"><FileSearch className="mt-0.5 h-5 w-5 text-primary" /><div className="flex-1"><h2 className="font-semibold">Review case {selected.id.slice(0,8)}</h2><p className="text-xs text-muted-foreground">{selected.trigger_reason}</p></div><Button variant="outline" size="sm" asChild><Link to="/officer/ai-compliance/$runId" params={{ runId: selected.run_id }}>Inspect evidence</Link></Button></div><Textarea className="mt-3" rows={3} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Required justification for override, clarification or escalation" /><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate("start")}>Start Review</Button><Button size="sm" className="bg-success text-success-foreground" disabled={action.isPending} onClick={() => action.mutate("confirm")}><CheckCircle2 className="mr-1 h-4 w-4" />Confirm AI Result</Button><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate("override")}><AlertTriangle className="mr-1 h-4 w-4" />Override</Button><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate("clarification")}>Request Clarification</Button><Button size="sm" variant="destructive" disabled={action.isPending} onClick={() => action.mutate("escalate")}>{action.isPending && <Loader2 className="mr-1 h-4 w-4 animate-spin" />}Escalate</Button></div></section>}
  </div>;
}