/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedOfficerRouteRouteImport } from './routes/_authenticated/officer/route'
import { Route as AuthenticatedVendorRouteRouteImport } from './routes/_authenticated/vendor/route'
import { Route as GovernmentSignInRouteImport } from './routes/government/sign-in'
import { Route as GovernmentSignUpRouteImport } from './routes/government/sign-up'
import { Route as VendorSignInRouteImport } from './routes/vendor/sign-in'
import { Route as VendorSignUpRouteImport } from './routes/vendor/sign-up'
import { Route as AuthenticatedOfficerAuditRouteImport } from './routes/_authenticated/officer/audit'
import { Route as AuthenticatedOfficerBidsRouteImport } from './routes/_authenticated/officer/bids'
import { Route as AuthenticatedOfficerDashboardRouteImport } from './routes/_authenticated/officer/dashboard'
import { Route as AuthenticatedOfficerDecisionsRouteImport } from './routes/_authenticated/officer/decisions'
import { Route as AuthenticatedOfficerHelpRouteImport } from './routes/_authenticated/officer/help'
import { Route as AuthenticatedOfficerHumanReviewRouteImport } from './routes/_authenticated/officer/human-review'
import { Route as AuthenticatedOfficerNotificationsRouteImport } from './routes/_authenticated/officer/notifications'
import { Route as AuthenticatedOfficerProfileRouteImport } from './routes/_authenticated/officer/profile'
import { Route as AuthenticatedOfficerReportsRouteImport } from './routes/_authenticated/officer/reports'
import { Route as AuthenticatedOfficerRulesRouteImport } from './routes/_authenticated/officer/rules'
import { Route as AuthenticatedOfficerSourcesRouteImport } from './routes/_authenticated/officer/sources'
import { Route as AuthenticatedOfficerUsersRouteImport } from './routes/_authenticated/officer/users'
import { Route as AuthenticatedOfficerVendorsRouteImport } from './routes/_authenticated/officer/vendors'
import { Route as AuthenticatedVendorBidPassportRouteImport } from './routes/_authenticated/vendor/bid-passport'
import { Route as AuthenticatedVendorComplianceRouteImport } from './routes/_authenticated/vendor/compliance'
import { Route as AuthenticatedVendorDashboardRouteImport } from './routes/_authenticated/vendor/dashboard'
import { Route as AuthenticatedVendorFindTendersRouteImport } from './routes/_authenticated/vendor/find-tenders'
import { Route as AuthenticatedVendorHelpRouteImport } from './routes/_authenticated/vendor/help'
import { Route as AuthenticatedVendorNotificationsRouteImport } from './routes/_authenticated/vendor/notifications'
import { Route as AuthenticatedVendorProfileRouteImport } from './routes/_authenticated/vendor/profile'
import { Route as AuthenticatedOfficerAiComplianceIndexRouteImport } from './routes/_authenticated/officer/ai-compliance.index'
import { Route as AuthenticatedOfficerAiComplianceRunIdRouteImport } from './routes/_authenticated/officer/ai-compliance.$runId'
import { Route as AuthenticatedOfficerTendersManageRouteImport } from './routes/_authenticated/officer/tenders/manage'
import { Route as AuthenticatedVendorMyBidsIndexRouteImport } from './routes/_authenticated/vendor/my-bids/index'
import { Route as AuthenticatedVendorMyBidsBidIdRouteImport } from './routes/_authenticated/vendor/my-bids/$bidId'
import { Route as AuthenticatedOfficerTendersCreateIndexRouteImport } from './routes/_authenticated/officer/tenders/create/index'
import { Route as AuthenticatedOfficerTendersCreateStageRouteImport } from './routes/_authenticated/officer/tenders/create/$stage'
import { Route as AuthenticatedVendorTendersTenderIdIndexRouteImport } from './routes/_authenticated/vendor/tenders/$tenderId/index'
import { Route as AuthenticatedVendorTendersTenderIdApplyStageRouteImport } from './routes/_authenticated/vendor/tenders/$tenderId/apply/$stage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOfficerRouteRoute =
  AuthenticatedOfficerRouteRouteImport.update({
    id: '/officer',
    path: '/officer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorRouteRoute =
  AuthenticatedVendorRouteRouteImport.update({
    id: '/vendor',
    path: '/vendor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const GovernmentSignInRoute = GovernmentSignInRouteImport.update({
  id: '/government/sign-in',
  path: '/government/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentSignUpRoute = GovernmentSignUpRouteImport.update({
  id: '/government/sign-up',
  path: '/government/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSignInRoute = VendorSignInRouteImport.update({
  id: '/vendor/sign-in',
  path: '/vendor/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSignUpRoute = VendorSignUpRouteImport.update({
  id: '/vendor/sign-up',
  path: '/vendor/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOfficerAuditRoute =
  AuthenticatedOfficerAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerBidsRoute =
  AuthenticatedOfficerBidsRouteImport.update({
    id: '/bids',
    path: '/bids',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerDashboardRoute =
  AuthenticatedOfficerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerDecisionsRoute =
  AuthenticatedOfficerDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerHelpRoute =
  AuthenticatedOfficerHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerHumanReviewRoute =
  AuthenticatedOfficerHumanReviewRouteImport.update({
    id: '/human-review',
    path: '/human-review',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerNotificationsRoute =
  AuthenticatedOfficerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerProfileRoute =
  AuthenticatedOfficerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerReportsRoute =
  AuthenticatedOfficerReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerRulesRoute =
  AuthenticatedOfficerRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerSourcesRoute =
  AuthenticatedOfficerSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerUsersRoute =
  AuthenticatedOfficerUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerVendorsRoute =
  AuthenticatedOfficerVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedVendorBidPassportRoute =
  AuthenticatedVendorBidPassportRouteImport.update({
    id: '/bid-passport',
    path: '/bid-passport',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorComplianceRoute =
  AuthenticatedVendorComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorDashboardRoute =
  AuthenticatedVendorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorFindTendersRoute =
  AuthenticatedVendorFindTendersRouteImport.update({
    id: '/find-tenders',
    path: '/find-tenders',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorHelpRoute = AuthenticatedVendorHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedVendorRouteRoute,
} as any)
const AuthenticatedVendorNotificationsRoute =
  AuthenticatedVendorNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorProfileRoute =
  AuthenticatedVendorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedOfficerAiComplianceIndexRoute =
  AuthenticatedOfficerAiComplianceIndexRouteImport.update({
    id: '/ai-compliance/',
    path: '/ai-compliance/',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerAiComplianceRunIdRoute =
  AuthenticatedOfficerAiComplianceRunIdRouteImport.update({
    id: '/ai-compliance/$runId',
    path: '/ai-compliance/$runId',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerTendersManageRoute =
  AuthenticatedOfficerTendersManageRouteImport.update({
    id: '/tenders/manage',
    path: '/tenders/manage',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedVendorMyBidsIndexRoute =
  AuthenticatedVendorMyBidsIndexRouteImport.update({
    id: '/my-bids/',
    path: '/my-bids/',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorMyBidsBidIdRoute =
  AuthenticatedVendorMyBidsBidIdRouteImport.update({
    id: '/my-bids/$bidId',
    path: '/my-bids/$bidId',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedOfficerTendersCreateIndexRoute =
  AuthenticatedOfficerTendersCreateIndexRouteImport.update({
    id: '/tenders/create/',
    path: '/tenders/create/',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedOfficerTendersCreateStageRoute =
  AuthenticatedOfficerTendersCreateStageRouteImport.update({
    id: '/tenders/create/$stage',
    path: '/tenders/create/$stage',
    getParentRoute: () => AuthenticatedOfficerRouteRoute,
  } as any)
const AuthenticatedVendorTendersTenderIdIndexRoute =
  AuthenticatedVendorTendersTenderIdIndexRouteImport.update({
    id: '/tenders/$tenderId/',
    path: '/tenders/$tenderId/',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)
const AuthenticatedVendorTendersTenderIdApplyStageRoute =
  AuthenticatedVendorTendersTenderIdApplyStageRouteImport.update({
    id: '/tenders/$tenderId/apply/$stage',
    path: '/tenders/$tenderId/apply/$stage',
    getParentRoute: () => AuthenticatedVendorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/officer': typeof AuthenticatedOfficerRouteRouteWithChildren
  '/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/government/sign-in': typeof GovernmentSignInRoute
  '/government/sign-up': typeof GovernmentSignUpRoute
  '/vendor/sign-in': typeof VendorSignInRoute
  '/vendor/sign-up': typeof VendorSignUpRoute
  '/officer/audit': typeof AuthenticatedOfficerAuditRoute
  '/officer/bids': typeof AuthenticatedOfficerBidsRoute
  '/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/officer/decisions': typeof AuthenticatedOfficerDecisionsRoute
  '/officer/help': typeof AuthenticatedOfficerHelpRoute
  '/officer/human-review': typeof AuthenticatedOfficerHumanReviewRoute
  '/officer/notifications': typeof AuthenticatedOfficerNotificationsRoute
  '/officer/profile': typeof AuthenticatedOfficerProfileRoute
  '/officer/reports': typeof AuthenticatedOfficerReportsRoute
  '/officer/rules': typeof AuthenticatedOfficerRulesRoute
  '/officer/sources': typeof AuthenticatedOfficerSourcesRoute
  '/officer/users': typeof AuthenticatedOfficerUsersRoute
  '/officer/vendors': typeof AuthenticatedOfficerVendorsRoute
  '/vendor/bid-passport': typeof AuthenticatedVendorBidPassportRoute
  '/vendor/compliance': typeof AuthenticatedVendorComplianceRoute
  '/vendor/dashboard': typeof AuthenticatedVendorDashboardRoute
  '/vendor/find-tenders': typeof AuthenticatedVendorFindTendersRoute
  '/vendor/help': typeof AuthenticatedVendorHelpRoute
  '/vendor/notifications': typeof AuthenticatedVendorNotificationsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/officer/ai-compliance/$runId': typeof AuthenticatedOfficerAiComplianceRunIdRoute
  '/officer/tenders/manage': typeof AuthenticatedOfficerTendersManageRoute
  '/vendor/my-bids/$bidId': typeof AuthenticatedVendorMyBidsBidIdRoute
  '/officer/ai-compliance/': typeof AuthenticatedOfficerAiComplianceIndexRoute
  '/vendor/my-bids/': typeof AuthenticatedVendorMyBidsIndexRoute
  '/officer/tenders/create/$stage': typeof AuthenticatedOfficerTendersCreateStageRoute
  '/officer/tenders/create/': typeof AuthenticatedOfficerTendersCreateIndexRoute
  '/vendor/tenders/$tenderId/': typeof AuthenticatedVendorTendersTenderIdIndexRoute
  '/vendor/tenders/$tenderId/apply/$stage': typeof AuthenticatedVendorTendersTenderIdApplyStageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/officer': typeof AuthenticatedOfficerRouteRouteWithChildren
  '/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/government/sign-in': typeof GovernmentSignInRoute
  '/government/sign-up': typeof GovernmentSignUpRoute
  '/vendor/sign-in': typeof VendorSignInRoute
  '/vendor/sign-up': typeof VendorSignUpRoute
  '/officer/audit': typeof AuthenticatedOfficerAuditRoute
  '/officer/bids': typeof AuthenticatedOfficerBidsRoute
  '/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/officer/decisions': typeof AuthenticatedOfficerDecisionsRoute
  '/officer/help': typeof AuthenticatedOfficerHelpRoute
  '/officer/human-review': typeof AuthenticatedOfficerHumanReviewRoute
  '/officer/notifications': typeof AuthenticatedOfficerNotificationsRoute
  '/officer/profile': typeof AuthenticatedOfficerProfileRoute
  '/officer/reports': typeof AuthenticatedOfficerReportsRoute
  '/officer/rules': typeof AuthenticatedOfficerRulesRoute
  '/officer/sources': typeof AuthenticatedOfficerSourcesRoute
  '/officer/users': typeof AuthenticatedOfficerUsersRoute
  '/officer/vendors': typeof AuthenticatedOfficerVendorsRoute
  '/vendor/bid-passport': typeof AuthenticatedVendorBidPassportRoute
  '/vendor/compliance': typeof AuthenticatedVendorComplianceRoute
  '/vendor/dashboard': typeof AuthenticatedVendorDashboardRoute
  '/vendor/find-tenders': typeof AuthenticatedVendorFindTendersRoute
  '/vendor/help': typeof AuthenticatedVendorHelpRoute
  '/vendor/notifications': typeof AuthenticatedVendorNotificationsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/officer/ai-compliance/$runId': typeof AuthenticatedOfficerAiComplianceRunIdRoute
  '/officer/tenders/manage': typeof AuthenticatedOfficerTendersManageRoute
  '/vendor/my-bids/$bidId': typeof AuthenticatedVendorMyBidsBidIdRoute
  '/officer/ai-compliance': typeof AuthenticatedOfficerAiComplianceIndexRoute
  '/vendor/my-bids': typeof AuthenticatedVendorMyBidsIndexRoute
  '/officer/tenders/create/$stage': typeof AuthenticatedOfficerTendersCreateStageRoute
  '/officer/tenders/create': typeof AuthenticatedOfficerTendersCreateIndexRoute
  '/vendor/tenders/$tenderId': typeof AuthenticatedVendorTendersTenderIdIndexRoute
  '/vendor/tenders/$tenderId/apply/$stage': typeof AuthenticatedVendorTendersTenderIdApplyStageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/_authenticated/officer': typeof AuthenticatedOfficerRouteRouteWithChildren
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteRouteWithChildren
  '/government/sign-in': typeof GovernmentSignInRoute
  '/government/sign-up': typeof GovernmentSignUpRoute
  '/vendor/sign-in': typeof VendorSignInRoute
  '/vendor/sign-up': typeof VendorSignUpRoute
  '/_authenticated/officer/audit': typeof AuthenticatedOfficerAuditRoute
  '/_authenticated/officer/bids': typeof AuthenticatedOfficerBidsRoute
  '/_authenticated/officer/dashboard': typeof AuthenticatedOfficerDashboardRoute
  '/_authenticated/officer/decisions': typeof AuthenticatedOfficerDecisionsRoute
  '/_authenticated/officer/help': typeof AuthenticatedOfficerHelpRoute
  '/_authenticated/officer/human-review': typeof AuthenticatedOfficerHumanReviewRoute
  '/_authenticated/officer/notifications': typeof AuthenticatedOfficerNotificationsRoute
  '/_authenticated/officer/profile': typeof AuthenticatedOfficerProfileRoute
  '/_authenticated/officer/reports': typeof AuthenticatedOfficerReportsRoute
  '/_authenticated/officer/rules': typeof AuthenticatedOfficerRulesRoute
  '/_authenticated/officer/sources': typeof AuthenticatedOfficerSourcesRoute
  '/_authenticated/officer/users': typeof AuthenticatedOfficerUsersRoute
  '/_authenticated/officer/vendors': typeof AuthenticatedOfficerVendorsRoute
  '/_authenticated/vendor/bid-passport': typeof AuthenticatedVendorBidPassportRoute
  '/_authenticated/vendor/compliance': typeof AuthenticatedVendorComplianceRoute
  '/_authenticated/vendor/dashboard': typeof AuthenticatedVendorDashboardRoute
  '/_authenticated/vendor/find-tenders': typeof AuthenticatedVendorFindTendersRoute
  '/_authenticated/vendor/help': typeof AuthenticatedVendorHelpRoute
  '/_authenticated/vendor/notifications': typeof AuthenticatedVendorNotificationsRoute
  '/_authenticated/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/_authenticated/officer/ai-compliance/$runId': typeof AuthenticatedOfficerAiComplianceRunIdRoute
  '/_authenticated/officer/tenders/manage': typeof AuthenticatedOfficerTendersManageRoute
  '/_authenticated/vendor/my-bids/$bidId': typeof AuthenticatedVendorMyBidsBidIdRoute
  '/_authenticated/officer/ai-compliance/': typeof AuthenticatedOfficerAiComplianceIndexRoute
  '/_authenticated/vendor/my-bids/': typeof AuthenticatedVendorMyBidsIndexRoute
  '/_authenticated/officer/tenders/create/$stage': typeof AuthenticatedOfficerTendersCreateStageRoute
  '/_authenticated/officer/tenders/create/': typeof AuthenticatedOfficerTendersCreateIndexRoute
  '/_authenticated/vendor/tenders/$tenderId/': typeof AuthenticatedVendorTendersTenderIdIndexRoute
  '/_authenticated/vendor/tenders/$tenderId/apply/$stage': typeof AuthenticatedVendorTendersTenderIdApplyStageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/help'
    | '/policies'
    | '/privacy'
    | '/reset-password'
    | '/sitemap'
    | '/terms'
    | '/officer'
    | '/vendor'
    | '/government/sign-in'
    | '/government/sign-up'
    | '/vendor/sign-in'
    | '/vendor/sign-up'
    | '/officer/audit'
    | '/officer/bids'
    | '/officer/dashboard'
    | '/officer/decisions'
    | '/officer/help'
    | '/officer/human-review'
    | '/officer/notifications'
    | '/officer/profile'
    | '/officer/reports'
    | '/officer/rules'
    | '/officer/sources'
    | '/officer/users'
    | '/officer/vendors'
    | '/vendor/bid-passport'
    | '/vendor/compliance'
    | '/vendor/dashboard'
    | '/vendor/find-tenders'
    | '/vendor/help'
    | '/vendor/notifications'
    | '/vendor/profile'
    | '/officer/ai-compliance/$runId'
    | '/officer/tenders/manage'
    | '/vendor/my-bids/$bidId'
    | '/officer/ai-compliance/'
    | '/vendor/my-bids/'
    | '/officer/tenders/create/$stage'
    | '/officer/tenders/create/'
    | '/vendor/tenders/$tenderId/'
    | '/vendor/tenders/$tenderId/apply/$stage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/help'
    | '/policies'
    | '/privacy'
    | '/reset-password'
    | '/sitemap'
    | '/terms'
    | '/officer'
    | '/vendor'
    | '/government/sign-in'
    | '/government/sign-up'
    | '/vendor/sign-in'
    | '/vendor/sign-up'
    | '/officer/audit'
    | '/officer/bids'
    | '/officer/dashboard'
    | '/officer/decisions'
    | '/officer/help'
    | '/officer/human-review'
    | '/officer/notifications'
    | '/officer/profile'
    | '/officer/reports'
    | '/officer/rules'
    | '/officer/sources'
    | '/officer/users'
    | '/officer/vendors'
    | '/vendor/bid-passport'
    | '/vendor/compliance'
    | '/vendor/dashboard'
    | '/vendor/find-tenders'
    | '/vendor/help'
    | '/vendor/notifications'
    | '/vendor/profile'
    | '/officer/ai-compliance/$runId'
    | '/officer/tenders/manage'
    | '/vendor/my-bids/$bidId'
    | '/officer/ai-compliance'
    | '/vendor/my-bids'
    | '/officer/tenders/create/$stage'
    | '/officer/tenders/create'
    | '/vendor/tenders/$tenderId'
    | '/vendor/tenders/$tenderId/apply/$stage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessibility'
    | '/auth'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/help'
    | '/policies'
    | '/privacy'
    | '/reset-password'
    | '/sitemap'
    | '/terms'
    | '/_authenticated/officer'
    | '/_authenticated/vendor'
    | '/government/sign-in'
    | '/government/sign-up'
    | '/vendor/sign-in'
    | '/vendor/sign-up'
    | '/_authenticated/officer/audit'
    | '/_authenticated/officer/bids'
    | '/_authenticated/officer/dashboard'
    | '/_authenticated/officer/decisions'
    | '/_authenticated/officer/help'
    | '/_authenticated/officer/human-review'
    | '/_authenticated/officer/notifications'
    | '/_authenticated/officer/profile'
    | '/_authenticated/officer/reports'
    | '/_authenticated/officer/rules'
    | '/_authenticated/officer/sources'
    | '/_authenticated/officer/users'
    | '/_authenticated/officer/vendors'
    | '/_authenticated/vendor/bid-passport'
    | '/_authenticated/vendor/compliance'
    | '/_authenticated/vendor/dashboard'
    | '/_authenticated/vendor/find-tenders'
    | '/_authenticated/vendor/help'
    | '/_authenticated/vendor/notifications'
    | '/_authenticated/vendor/profile'
    | '/_authenticated/officer/ai-compliance/$runId'
    | '/_authenticated/officer/tenders/manage'
    | '/_authenticated/vendor/my-bids/$bidId'
    | '/_authenticated/officer/ai-compliance/'
    | '/_authenticated/vendor/my-bids/'
    | '/_authenticated/officer/tenders/create/$stage'
    | '/_authenticated/officer/tenders/create/'
    | '/_authenticated/vendor/tenders/$tenderId/'
    | '/_authenticated/vendor/tenders/$tenderId/apply/$stage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  GovernmentSignInRoute: typeof GovernmentSignInRoute
  GovernmentSignUpRoute: typeof GovernmentSignUpRoute
  VendorSignInRoute: typeof VendorSignInRoute
  VendorSignUpRoute: typeof VendorSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/officer': {
      id: '/_authenticated/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof AuthenticatedOfficerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/government/sign-in': {
      id: '/government/sign-in'
      path: '/government/sign-in'
      fullPath: '/government/sign-in'
      preLoaderRoute: typeof GovernmentSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government/sign-up': {
      id: '/government/sign-up'
      path: '/government/sign-up'
      fullPath: '/government/sign-up'
      preLoaderRoute: typeof GovernmentSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/sign-in': {
      id: '/vendor/sign-in'
      path: '/vendor/sign-in'
      fullPath: '/vendor/sign-in'
      preLoaderRoute: typeof VendorSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/sign-up': {
      id: '/vendor/sign-up'
      path: '/vendor/sign-up'
      fullPath: '/vendor/sign-up'
      preLoaderRoute: typeof VendorSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/officer/audit': {
      id: '/_authenticated/officer/audit'
      path: '/audit'
      fullPath: '/officer/audit'
      preLoaderRoute: typeof AuthenticatedOfficerAuditRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/bids': {
      id: '/_authenticated/officer/bids'
      path: '/bids'
      fullPath: '/officer/bids'
      preLoaderRoute: typeof AuthenticatedOfficerBidsRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/dashboard': {
      id: '/_authenticated/officer/dashboard'
      path: '/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof AuthenticatedOfficerDashboardRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/decisions': {
      id: '/_authenticated/officer/decisions'
      path: '/decisions'
      fullPath: '/officer/decisions'
      preLoaderRoute: typeof AuthenticatedOfficerDecisionsRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/help': {
      id: '/_authenticated/officer/help'
      path: '/help'
      fullPath: '/officer/help'
      preLoaderRoute: typeof AuthenticatedOfficerHelpRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/human-review': {
      id: '/_authenticated/officer/human-review'
      path: '/human-review'
      fullPath: '/officer/human-review'
      preLoaderRoute: typeof AuthenticatedOfficerHumanReviewRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/notifications': {
      id: '/_authenticated/officer/notifications'
      path: '/notifications'
      fullPath: '/officer/notifications'
      preLoaderRoute: typeof AuthenticatedOfficerNotificationsRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/profile': {
      id: '/_authenticated/officer/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof AuthenticatedOfficerProfileRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/reports': {
      id: '/_authenticated/officer/reports'
      path: '/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof AuthenticatedOfficerReportsRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/rules': {
      id: '/_authenticated/officer/rules'
      path: '/rules'
      fullPath: '/officer/rules'
      preLoaderRoute: typeof AuthenticatedOfficerRulesRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/sources': {
      id: '/_authenticated/officer/sources'
      path: '/sources'
      fullPath: '/officer/sources'
      preLoaderRoute: typeof AuthenticatedOfficerSourcesRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/users': {
      id: '/_authenticated/officer/users'
      path: '/users'
      fullPath: '/officer/users'
      preLoaderRoute: typeof AuthenticatedOfficerUsersRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/vendors': {
      id: '/_authenticated/officer/vendors'
      path: '/vendors'
      fullPath: '/officer/vendors'
      preLoaderRoute: typeof AuthenticatedOfficerVendorsRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/vendor/bid-passport': {
      id: '/_authenticated/vendor/bid-passport'
      path: '/bid-passport'
      fullPath: '/vendor/bid-passport'
      preLoaderRoute: typeof AuthenticatedVendorBidPassportRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/compliance': {
      id: '/_authenticated/vendor/compliance'
      path: '/compliance'
      fullPath: '/vendor/compliance'
      preLoaderRoute: typeof AuthenticatedVendorComplianceRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/dashboard': {
      id: '/_authenticated/vendor/dashboard'
      path: '/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof AuthenticatedVendorDashboardRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/find-tenders': {
      id: '/_authenticated/vendor/find-tenders'
      path: '/find-tenders'
      fullPath: '/vendor/find-tenders'
      preLoaderRoute: typeof AuthenticatedVendorFindTendersRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/help': {
      id: '/_authenticated/vendor/help'
      path: '/help'
      fullPath: '/vendor/help'
      preLoaderRoute: typeof AuthenticatedVendorHelpRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/notifications': {
      id: '/_authenticated/vendor/notifications'
      path: '/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof AuthenticatedVendorNotificationsRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/profile': {
      id: '/_authenticated/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof AuthenticatedVendorProfileRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/officer/ai-compliance/': {
      id: '/_authenticated/officer/ai-compliance/'
      path: '/ai-compliance'
      fullPath: '/officer/ai-compliance/'
      preLoaderRoute: typeof AuthenticatedOfficerAiComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/ai-compliance/$runId': {
      id: '/_authenticated/officer/ai-compliance/$runId'
      path: '/ai-compliance/$runId'
      fullPath: '/officer/ai-compliance/$runId'
      preLoaderRoute: typeof AuthenticatedOfficerAiComplianceRunIdRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/tenders/manage': {
      id: '/_authenticated/officer/tenders/manage'
      path: '/tenders/manage'
      fullPath: '/officer/tenders/manage'
      preLoaderRoute: typeof AuthenticatedOfficerTendersManageRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/vendor/my-bids/': {
      id: '/_authenticated/vendor/my-bids/'
      path: '/my-bids'
      fullPath: '/vendor/my-bids/'
      preLoaderRoute: typeof AuthenticatedVendorMyBidsIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/my-bids/$bidId': {
      id: '/_authenticated/vendor/my-bids/$bidId'
      path: '/my-bids/$bidId'
      fullPath: '/vendor/my-bids/$bidId'
      preLoaderRoute: typeof AuthenticatedVendorMyBidsBidIdRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/officer/tenders/create/': {
      id: '/_authenticated/officer/tenders/create/'
      path: '/tenders/create'
      fullPath: '/officer/tenders/create/'
      preLoaderRoute: typeof AuthenticatedOfficerTendersCreateIndexRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/officer/tenders/create/$stage': {
      id: '/_authenticated/officer/tenders/create/$stage'
      path: '/tenders/create/$stage'
      fullPath: '/officer/tenders/create/$stage'
      preLoaderRoute: typeof AuthenticatedOfficerTendersCreateStageRouteImport
      parentRoute: typeof AuthenticatedOfficerRouteRoute
    }
    '/_authenticated/vendor/tenders/$tenderId/': {
      id: '/_authenticated/vendor/tenders/$tenderId/'
      path: '/tenders/$tenderId'
      fullPath: '/vendor/tenders/$tenderId/'
      preLoaderRoute: typeof AuthenticatedVendorTendersTenderIdIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
    '/_authenticated/vendor/tenders/$tenderId/apply/$stage': {
      id: '/_authenticated/vendor/tenders/$tenderId/apply/$stage'
      path: '/tenders/$tenderId/apply/$stage'
      fullPath: '/vendor/tenders/$tenderId/apply/$stage'
      preLoaderRoute: typeof AuthenticatedVendorTendersTenderIdApplyStageRouteImport
      parentRoute: typeof AuthenticatedVendorRouteRoute
    }
  }
}

interface AuthenticatedOfficerRouteRouteChildren {
  AuthenticatedOfficerAuditRoute: typeof AuthenticatedOfficerAuditRoute
  AuthenticatedOfficerBidsRoute: typeof AuthenticatedOfficerBidsRoute
  AuthenticatedOfficerDashboardRoute: typeof AuthenticatedOfficerDashboardRoute
  AuthenticatedOfficerDecisionsRoute: typeof AuthenticatedOfficerDecisionsRoute
  AuthenticatedOfficerHelpRoute: typeof AuthenticatedOfficerHelpRoute
  AuthenticatedOfficerHumanReviewRoute: typeof AuthenticatedOfficerHumanReviewRoute
  AuthenticatedOfficerNotificationsRoute: typeof AuthenticatedOfficerNotificationsRoute
  AuthenticatedOfficerProfileRoute: typeof AuthenticatedOfficerProfileRoute
  AuthenticatedOfficerReportsRoute: typeof AuthenticatedOfficerReportsRoute
  AuthenticatedOfficerRulesRoute: typeof AuthenticatedOfficerRulesRoute
  AuthenticatedOfficerSourcesRoute: typeof AuthenticatedOfficerSourcesRoute
  AuthenticatedOfficerUsersRoute: typeof AuthenticatedOfficerUsersRoute
  AuthenticatedOfficerVendorsRoute: typeof AuthenticatedOfficerVendorsRoute
  AuthenticatedOfficerAiComplianceRunIdRoute: typeof AuthenticatedOfficerAiComplianceRunIdRoute
  AuthenticatedOfficerTendersManageRoute: typeof AuthenticatedOfficerTendersManageRoute
  AuthenticatedOfficerAiComplianceIndexRoute: typeof AuthenticatedOfficerAiComplianceIndexRoute
  AuthenticatedOfficerTendersCreateStageRoute: typeof AuthenticatedOfficerTendersCreateStageRoute
  AuthenticatedOfficerTendersCreateIndexRoute: typeof AuthenticatedOfficerTendersCreateIndexRoute
}

const AuthenticatedOfficerRouteRouteChildren: AuthenticatedOfficerRouteRouteChildren =
  {
    AuthenticatedOfficerAuditRoute: AuthenticatedOfficerAuditRoute,
    AuthenticatedOfficerBidsRoute: AuthenticatedOfficerBidsRoute,
    AuthenticatedOfficerDashboardRoute: AuthenticatedOfficerDashboardRoute,
    AuthenticatedOfficerDecisionsRoute: AuthenticatedOfficerDecisionsRoute,
    AuthenticatedOfficerHelpRoute: AuthenticatedOfficerHelpRoute,
    AuthenticatedOfficerHumanReviewRoute: AuthenticatedOfficerHumanReviewRoute,
    AuthenticatedOfficerNotificationsRoute:
      AuthenticatedOfficerNotificationsRoute,
    AuthenticatedOfficerProfileRoute: AuthenticatedOfficerProfileRoute,
    AuthenticatedOfficerReportsRoute: AuthenticatedOfficerReportsRoute,
    AuthenticatedOfficerRulesRoute: AuthenticatedOfficerRulesRoute,
    AuthenticatedOfficerSourcesRoute: AuthenticatedOfficerSourcesRoute,
    AuthenticatedOfficerUsersRoute: AuthenticatedOfficerUsersRoute,
    AuthenticatedOfficerVendorsRoute: AuthenticatedOfficerVendorsRoute,
    AuthenticatedOfficerAiComplianceRunIdRoute:
      AuthenticatedOfficerAiComplianceRunIdRoute,
    AuthenticatedOfficerTendersManageRoute:
      AuthenticatedOfficerTendersManageRoute,
    AuthenticatedOfficerAiComplianceIndexRoute:
      AuthenticatedOfficerAiComplianceIndexRoute,
    AuthenticatedOfficerTendersCreateStageRoute:
      AuthenticatedOfficerTendersCreateStageRoute,
    AuthenticatedOfficerTendersCreateIndexRoute:
      AuthenticatedOfficerTendersCreateIndexRoute,
  }

const AuthenticatedOfficerRouteRouteWithChildren =
  AuthenticatedOfficerRouteRoute._addFileChildren(
    AuthenticatedOfficerRouteRouteChildren,
  )

interface AuthenticatedVendorRouteRouteChildren {
  AuthenticatedVendorBidPassportRoute: typeof AuthenticatedVendorBidPassportRoute
  AuthenticatedVendorComplianceRoute: typeof AuthenticatedVendorComplianceRoute
  AuthenticatedVendorDashboardRoute: typeof AuthenticatedVendorDashboardRoute
  AuthenticatedVendorFindTendersRoute: typeof AuthenticatedVendorFindTendersRoute
  AuthenticatedVendorHelpRoute: typeof AuthenticatedVendorHelpRoute
  AuthenticatedVendorNotificationsRoute: typeof AuthenticatedVendorNotificationsRoute
  AuthenticatedVendorProfileRoute: typeof AuthenticatedVendorProfileRoute
  AuthenticatedVendorMyBidsBidIdRoute: typeof AuthenticatedVendorMyBidsBidIdRoute
  AuthenticatedVendorMyBidsIndexRoute: typeof AuthenticatedVendorMyBidsIndexRoute
  AuthenticatedVendorTendersTenderIdIndexRoute: typeof AuthenticatedVendorTendersTenderIdIndexRoute
  AuthenticatedVendorTendersTenderIdApplyStageRoute: typeof AuthenticatedVendorTendersTenderIdApplyStageRoute
}

const AuthenticatedVendorRouteRouteChildren: AuthenticatedVendorRouteRouteChildren =
  {
    AuthenticatedVendorBidPassportRoute: AuthenticatedVendorBidPassportRoute,
    AuthenticatedVendorComplianceRoute: AuthenticatedVendorComplianceRoute,
    AuthenticatedVendorDashboardRoute: AuthenticatedVendorDashboardRoute,
    AuthenticatedVendorFindTendersRoute: AuthenticatedVendorFindTendersRoute,
    AuthenticatedVendorHelpRoute: AuthenticatedVendorHelpRoute,
    AuthenticatedVendorNotificationsRoute:
      AuthenticatedVendorNotificationsRoute,
    AuthenticatedVendorProfileRoute: AuthenticatedVendorProfileRoute,
    AuthenticatedVendorMyBidsBidIdRoute: AuthenticatedVendorMyBidsBidIdRoute,
    AuthenticatedVendorMyBidsIndexRoute: AuthenticatedVendorMyBidsIndexRoute,
    AuthenticatedVendorTendersTenderIdIndexRoute:
      AuthenticatedVendorTendersTenderIdIndexRoute,
    AuthenticatedVendorTendersTenderIdApplyStageRoute:
      AuthenticatedVendorTendersTenderIdApplyStageRoute,
  }

const AuthenticatedVendorRouteRouteWithChildren =
  AuthenticatedVendorRouteRoute._addFileChildren(
    AuthenticatedVendorRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOfficerRouteRoute: typeof AuthenticatedOfficerRouteRouteWithChildren
  AuthenticatedVendorRouteRoute: typeof AuthenticatedVendorRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOfficerRouteRoute: AuthenticatedOfficerRouteRouteWithChildren,
  AuthenticatedVendorRouteRoute: AuthenticatedVendorRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  GovernmentSignInRoute: GovernmentSignInRoute,
  GovernmentSignUpRoute: GovernmentSignUpRoute,
  VendorSignInRoute: VendorSignInRoute,
  VendorSignUpRoute: VendorSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
